#!/usr/bin/env bash
set -e

echo 'Installing Java...'
yum install -y java

echo 'Installing unzip...'
yum install -y unzip

echo 'Installing pip...'
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
rm get-pip.py

echo 'Installing python:vk...'
pip install vk

echo 'Downloading Spring XD...'
wget https://repo.spring.io/libs-release/org/springframework/xd/spring-xd/1.3.1.RELEASE/spring-xd-1.3.1.RELEASE-dist.zip

echo 'Extracting Spring XD distribution...'
unzip spring-xd-1.3.1.RELEASE-dist.zip
rm spring-xd-1.3.1.RELEASE-dist.zip

echo 'Setting Spring XD up...'
export XD_HOME=spring-xd-1.3.1.RELEASE/xd/
